"""create_comment_analyses_table

Revision ID: 1d256c555fda
Revises: db0e7bd4bbec
Create Date: 2026-09-22 08:01:55.587625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d256c555fda'
down_revision: Union[str, Sequence[str], None] = 'db0e7bd4bbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_analyses_comment_id'), 'comment_analyses', ['comment_id'], unique=True)
    op.create_index(op.f('ix_comment_analyses_id'), 'comment_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_comment_analyses_is_actionable'), 'comment_analyses', ['is_actionable'], unique=False)
    op.create_index(op.f('ix_comment_analyses_is_question'), 'comment_analyses', ['is_question'], unique=False)
    op.create_index(op.f('ix_comment_analyses_sentiment'), 'comment_analyses', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_analyses_sentiment'), table_name='comment_analyses')
    op.drop_index(op.f('ix_comment_analyses_is_question'), table_name='comment_analyses')
    op.drop_index(op.f('ix_comment_analyses_is_actionable'), table_name='comment_analyses')
    op.drop_index(op.f('ix_comment_analyses_id'), table_name='comment_analyses')
    op.drop_index(op.f('ix_comment_analyses_comment_id'), table_name='comment_analyses')
    op.drop_table('comment_analyses')
    # ### end Alembic commands ###
